version: "3.8"

services:
  mariadb:
    image: mariadb:11.4
    container_name: gowayki-mariadb
    restart: unless-stopped
    environment:
      MARIADB_ROOT_PASSWORD: rootpass
      MARIADB_DATABASE: gowayki_db
      MARIADB_USER: gowayki_user
      MARIADB_PASSWORD: gowayki_pass
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql

volumes:
  mariadb_data: